version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Unit tests
          command: |
            docker-compose build
            docker-compose run --rm app phpunit
